before_install:
  - gem update bundler rake
branches:
  only:
    - master
env:
  global:
    secure: | # CODECLIMATE_REPO_TOKEN
      EEoiWSHrAnv1VAlN6msYZPWcdKohINin6vmghWn54uvNcowgLwIr/0S5+Cx7
      YqY/iYA0OzELX5j5pTgMHLroG4kkbgTnBQe09pFGxhoqA0WOp/uZkyX6dFro
      yatmOosa1UUiw4aZogfjv2KdP18oILxV3d+lIfqZgUb7o9bTzbw=
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - ruby-head
script: bundle exec rspec
