branches:
  only:
    - master
env:
  global:
    secure: | # CODECLIMATE_REPO_TOKEN
      mWbGKP4AUdfjjK0Vx8UqZVA/5ERfXxQ0sz+asOriGq8GkMmIh9fkpV1cto5I
      PD4AOgJiYBh17XZ1igxm8Khwhw39Jf2QMGSW+WuMI6h94CUdwHxe4IN+0mkm
      x7I/BnsJ8kRSDYNxxH3XM6ktGBICaAnWrvAkeOUV7enhYqN6e+s=
language: ruby
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: ruby-head
rvm:
  - 1.9.3
  - "2.0"
  - "2.1"
  - ruby-head
script: bundle exec rspec
